using System;
using System.Collections.Generic;
using System.Text;

namespace PurpleMoon.Types
{
    public static class FontCharIndex
    {
        public const int exclamation = 0;
        public const int quotation = 1;
        public const int numberSign = 2;
        public const int dollarSign = 3;
        public const int percent = 4;
        public const int ampersand = 5;
        public const int apostrophe = 6;
        public const int bracketLeft = 7;
        public const int bracketRight = 8;
        public const int multiply = 9;
        public const int add = 10;
        public const int comma = 11;
        public const int minus = 12;
        public const int period = 13;
        public const int slash = 14;
        public const int n0 = 15;
        public const int n1 = 16;
        public const int n2 = 17;
        public const int n3 = 18;
        public const int n4 = 19;
        public const int n5 = 20;
        public const int n6 = 21;
        public const int n7 = 22;
        public const int n8 = 23;
        public const int n9 = 24;
        public const int colon = 25;
        public const int semiColon = 26;
        public const int arrowLeft = 27;
        public const int equals = 28;
        public const int arrowRight = 29;
        public const int question = 30;
        public const int at = 31;
        public const int capA = 32;
        public const int capB = 33;
        public const int capC = 34;
        public const int capD = 35;
        public const int capE = 36;
        public const int capF = 37;
        public const int capG = 38;
        public const int capH = 39;
        public const int capI = 40;
        public const int capJ = 41;
        public const int capK = 42;
        public const int capL = 43;
        public const int capM = 44;
        public const int capN = 45;
        public const int capO = 46;
        public const int capP = 47;
        public const int capQ = 48;
        public const int capR = 49;
        public const int capS = 50;
        public const int capT = 51;
        public const int capU = 52;
        public const int capV = 53;
        public const int capW = 54;
        public const int capX = 55;
        public const int capY = 56;
        public const int capZ = 57;
        public const int sqBracketL = 58;
        public const int backSlash = 59;
        public const int sqBracketR = 60;
        public const int upArrow = 61;
        public const int underscore = 62;
        public const int tilde = 63;
        public const int a = 64;
        public const int b = 65;
        public const int c = 66;
        public const int d = 67;
        public const int e = 68;
        public const int f = 69;
        public const int g = 70;
        public const int h = 71;
        public const int i = 72;
        public const int j = 73;
        public const int k = 74;
        public const int l = 75;
        public const int m = 76;
        public const int n = 77;
        public const int o = 78;
        public const int p = 79;
        public const int q = 80;
        public const int r = 81;
        public const int s = 82;
        public const int t = 83;
        public const int u = 84;
        public const int v = 85;
        public const int w = 86;
        public const int x = 87;
        public const int y = 88;
        public const int z = 89;
        public const int crBracketL = 90;
        public const int div = 91;
        public const int crBracketR = 92;
        public const int squiggle = 93;
    }
}
